#!/bin/bash

if [ $# -eq 0 ]
then
  echo "Must supply index of prof test file"
  exit
fi

cd player/; make clean; make PROF=1; cd ../;

awsrun ./player/leiserchess my_tests/prof$1
gprof ./player/leiserchess log.awsrun/gmon.out
