#!/bin/bash

#aws="--aws"
if [ $1 ]
then
  ./gen_tests.py $1 my_tests/
fi

cd player/; make clean; make TEST=1; cd ../;
#cd stable/; make clean; make; cd ../;
./run_tests.py player/leiserchess my_tests/ $aws
